insert into book (title,author,rating,is_lent) values ('Anansi Boys','Neil Gaiman', 7, false);
insert into book (title,author,rating,is_lent) values ('American Gods','Neil Gaiman', 8, false);
insert into book (title,author,rating,is_lent) values ('Twilight','Stephanie Meyer', 1, false);
insert into book (title,author,rating,is_lent) values ('Narrenturm','Andrzej Sapkowski', 7, true);
insert into book (title,author,rating,is_lent) values ('Boży Bojownicy','Andrzej Sapkowski', 6, false);
insert into book (title,author,rating,is_lent) values ('Kraina Chichów','Carroll, Jonathan',10, false)
insert into book (title,author,rating,is_lent) values ('Dziecko na niebie','Carroll, Jonathan',10, false)
insert into book (title,author,rating,is_lent) values ('Cud w Carville','Martin, Betty',10, false)
insert into book (title,author,rating,is_lent) values ('Przeminęło z wiatrem','Mitchell, Margaret',10, false)
insert into book (title,author,rating,is_lent) values ('Kot w stanie czystym','Pratchett, Terry',10, false)
insert into book (title,author,rating,is_lent) values ('Zew Cthulhu','Lovecraft, H.P.',10, false)
insert into book (title,author,rating,is_lent) values ('Poza ciszą','Carroll, Jonathan',10, false)
insert into book (title,author,rating,is_lent) values ('Śpiąc w płomieniu','Carroll, Jonathan',10, false)
insert into book (title,author,rating,is_lent) values ('Całując Ul','Carroll, Jonathan',10, false)
insert into book (title,author,rating,is_lent) values ('Drewniane morze','Carroll, Jonathan',10, false)
insert into book (title,author,rating,is_lent) values ('Upiorna dłoń','Carroll, Jonathan',10, false)
insert into book (title,author,rating,is_lent) values ('Cylinder Heidelberga','Carroll, Jonathan',10, false)
insert into book (title,author,rating,is_lent) values ('Na pastwę aniołów','Carroll, Jonathan',10, false)
insert into book (title,author,rating,is_lent) values ('Zaślubiny patyków','Carroll, Jonathan',10, false)
insert into book (title,author,rating,is_lent) values ('Ptasiek','Wharton, William',10, false)
insert into book (title,author,rating,is_lent) values ('Niedziela palmowa','Vonnegut, Kurt',10, false)
insert into book (title,author,rating,is_lent) values ('Cień wiatru','Zafón, Carlos Ruiz',10, false)
insert into book (title,author,rating,is_lent) values ('Syreny z Tytana','Vonnegut, Kurt',10, false)
insert into book (title,author,rating,is_lent) values ('Rzeźnia numer 5','Vonnegut, Kurt',10, false)
insert into book (title,author,rating,is_lent) values ('Hokus Pokus','Vonnegut, Kurt',10, false)
insert into book (title,author,rating,is_lent) values ('Księżniczka Angina','Topor, Ronald',10, false)
insert into book (title,author,rating,is_lent) values ('Rozpacz','Nabokov, Vladimir',10, false)
insert into book (title,author,rating,is_lent) values ('Oko','Nabokov, Vladimir',10, false)
insert into book (title,author,rating,is_lent) values ('Miłość jest straszna','Filipacchi, Amanda',10, false)
insert into book (title,author,rating,is_lent) values ('Ex libris','Fadiman, Anne',10, false)
insert into book (title,author,rating,is_lent) values ('W ogóle i szczególe','Fadiman, Anne',10, false)
insert into book (title,author,rating,is_lent) values ('Co gryzie Gilberta Grape'a','Hedges, Peter',10, false)
insert into book (title,author,rating,is_lent) values ('Dzikość serca','Gifford, Barry',10, false)
insert into book (title,author,rating,is_lent) values ('Jak chodzić na wysokich obcasach','Morton, Camilla',10, false)
insert into book (title,author,rating,is_lent) values ('Belcanto','Patchett, Ann',10, false)
insert into book (title,author,rating,is_lent) values ('Moja siostra, moja miłość','Oates, Joyce Carol',10, false)
insert into book (title,author,rating,is_lent) values ('Trylogia nowojorska','Auster, Paul',10, false)
insert into book (title,author,rating,is_lent) values ('Andy Warhol. Życie i śmierć','Bockris, Victor',10, false)
insert into book (title,author,rating,is_lent) values ('Woda dla słoni','Gruen, Sara',10, false)
insert into book (title,author,rating,is_lent) values ('Zanim dopadnie nas czas','Egan, Jennifer',10, false)
insert into book (title,author,rating,is_lent) values ('Sinobrody','Vonnegut, Kurt',10, false)
insert into book (title,author,rating,is_lent) values ('Artemis Fowl','Colfer, Eoin',10, false)
insert into book (title,author,rating,is_lent) values ('Artemis Fowl. Arktyczna przygoda','Colfer, Eoin',10, false)
insert into book (title,author,rating,is_lent) values ('Artemis Fowl. Kod wieczności','Colfer, Eoin',10, false)
insert into book (title,author,rating,is_lent) values ('Artemis Fowl. Fortel wróżki','Colfer, Eoin',10, false)
insert into book (title,author,rating,is_lent) values ('Artemis Fowl. Zaginiona kolonia','Colfer, Eoin',10, false)
insert into book (title,author,rating,is_lent) values ('Artemis Fowl. Paradoks czasu','Colfer, Eoin',10, false)
insert into book (title,author,rating,is_lent) values ('Lista życzeń','Colfer, Eoin',10, false)
insert into book (title,author,rating,is_lent) values ('Przykry początek','Snicket, Lemony',10, false)
insert into book (title,author,rating,is_lent) values ('Gabinet gadów','Snicket, Lemony',10, false)
insert into book (title,author,rating,is_lent) values ('Ogromne okno','Snicket, Lemony',10, false)
insert into book (title,author,rating,is_lent) values ('Tartak tortur','Snicket, Lemony',10, false)
insert into book (title,author,rating,is_lent) values ('Akademia antypatii','Snicket, Lemony',10, false)
insert into book (title,author,rating,is_lent) values ('Winda widmo','Snicket, Lemony',10, false)
insert into book (title,author,rating,is_lent) values ('Wredna wioska','Snicket, Lemony',10, false)
insert into book (title,author,rating,is_lent) values ('Szkodliwy szpital','Snicket, Lemony',10, false)
insert into book (title,author,rating,is_lent) values ('Krwiożerczy karnawał','Snicket, Lemony',10, false)
insert into book (title,author,rating,is_lent) values ('Zjezdne zbocze','Snicket, Lemony',10, false)
insert into book (title,author,rating,is_lent) values ('Groźna grota','Snicket, Lemony',10, false)
insert into book (title,author,rating,is_lent) values ('Przedostatnia pułapka','Snicket, Lemony',10, false)
insert into book (title,author,rating,is_lent) values ('Koniec Końców','Snicket, Lemony',10, false)
insert into book (title,author,rating,is_lent) values ('Białe jabłka','Carroll, Jonathan',10, false)
insert into book (title,author,rating,is_lent) values ('Szklana zupa','Carroll, Jonathan',10, false)
insert into book (title,author,rating,is_lent) values ('Kości księżyca','Carroll, Jonathan',10, false)
insert into book (title,author,rating,is_lent) values ('Oko dnia','Carroll, Jonathan',10, false)
insert into book (title,author,rating,is_lent) values ('Muzeum Psów','Carroll, Jonathan',10, false)
insert into book (title,author,rating,is_lent) values ('Zakochany duch','Carroll, Jonathan',10, false)
insert into book (title,author,rating,is_lent) values ('Blondynka','Oates, Joyce Carol',10, false)
insert into book (title,author,rating,is_lent) values ('Nostalgia anioła','Sebold, Alice',10, false)
insert into book (title,author,rating,is_lent) values ('Obłok','Filipacchi, Amanda',10, false)
insert into book (title,author,rating,is_lent) values ('Podwójne życie mojej córki','Campbell, Bebe Moore',10, false)
insert into book (title,author,rating,is_lent) values ('Stowarzyszenie umarłych poetów','Kleinbaum, Nancy H.',10, false)
insert into book (title,author,rating,is_lent) values ('Strzeliłam do Elvisa','Eversz, Robert M.',10, false)
insert into book (title,author,rating,is_lent) values ('Szkoła uczuć','Sittenfeld, Curtis',10, false)
insert into book (title,author,rating,is_lent) values ('Trzy stygmaty Palmera Eldritcha','Dick, Philip K.',10, false)
insert into book (title,author,rating,is_lent) values ('Raport mniejszości','Dick, Philip K.',10, false)
insert into book (title,author,rating,is_lent) values ('Wywiad z wampirem','Rice, Anne',10, false)
insert into book (title,author,rating,is_lent) values ('Zapałka na zakręcie','Siesicka, Krystyna',10, false)
insert into book (title,author,rating,is_lent) values ('Doły','Sachar, Louis',10, false)
insert into book (title,author,rating,is_lent) values ('Koralina','Gaiman, Neil',10, false)
insert into book (title,author,rating,is_lent) values ('Dedektyw Monk i straż pożarna','Goldberg, Lee',10, false)
insert into book (title,author,rating,is_lent) values ('Psy z Wieży Babel','Parkhurst, Carolyn',10, false)
insert into book (title,author,rating,is_lent) values ('Oko dnia (Twarda oprawa)','Carroll, Jonathan',10, false)
insert into book (title,author,rating,is_lent) values ('Artemis Fowl (Wersja angielska)','Colfer, Eoin',10, false)
insert into book (title,author,rating,is_lent) values ('W Krainie Kota','Terakowska, Dorota',10, false)
insert into book (title,author,rating,is_lent) values ('Więzień nieba','Zafón, Carlos Ruiz',10, false)
insert into book (title,author,rating,is_lent) values ('Wichrowe Wzórza','Brontë, Emily',10, false)
insert into book (title,author,rating,is_lent) values ('Poradnik pozytywnego myślenia','Quick, Matthew',10, false)
insert into book (title,author,rating,is_lent) values ('Sztuka uprawiania róż z kolcami','Dilloway, Margaret',10, false)
insert into book (title,author,rating,is_lent) values ('Gracze','Chaczko, Renata',10, false)
insert into book (title,author,rating,is_lent) values ('Niebieski notatnik','Levine, James A.',10, false)
insert into book (title,author,rating,is_lent) values ('Cyrk nocy','Morgenstern, Erin',10, false)
insert into book (title,author,rating,is_lent) values ('Trzy oblicza pożądania','Hart, Megan',10, false)
insert into book (title,author,rating,is_lent) values ('Chéri','Colette, Sidonie Gabrielle',10, false)
insert into book (title,author,rating,is_lent) values ('Inne głosy, inne ściany','Capote, Truman',10, false)
insert into book (title,author,rating,is_lent) values ('Z zimną krwią','Capote, Truman',10, false)
insert into book (title,author,rating,is_lent) values ('Dzieci północy','Rushdie, Salman',10, false)
insert into book (title,author,rating,is_lent) values ('Gra anioła','Zafón, Carlos Ruiz',10, false)
insert into book (title,author,rating,is_lent) values ('Magia domowa','Cunningham, Scott',10, false)
insert into book (title,author,rating,is_lent) values ('Lawendowy pokój','George, Nina',10, false)
insert into book (title,author,rating,is_lent) values ('Skradziona','Sánchez, Clara',10, false)
insert into book (title,author,rating,is_lent) values ('Walka kotów','Mendoza, Eduardo',10, false)
insert into book (title,author,rating,is_lent) values ('Pozostawieni','Perrotta, Tom',10, false)
insert into book (title,author,rating,is_lent) values ('Klub kąpielowyangielskich dam','Zitwer, Barbara J.',10, false)
insert into book (title,author,rating,is_lent) values ('Stulatek, który wyskoczył przez okno i zniknął','Jonasson, Jonas',10, false)
insert into book (title,author,rating,is_lent) values ('Dziennik Bridget Jones. Szalejąc za facetem','Fielding, Helen',10, false)
insert into book (title,author,rating,is_lent) values ('O mały włos','Colfer, Eoin',10, false)
insert into book (title,author,rating,is_lent) values ('Rzecz o mych smutnych dziwkach','Márquez, Gabriel Gracía',10, false)
insert into book (title,author,rating,is_lent) values ('Bezcenny','Miłoszewski, Zygmunt',10, false)
insert into book (title,author,rating,is_lent) values ('Hopeless','Hoover, Colleen',10, false)
insert into book (title,author,rating,is_lent) values ('Skazana','Kent, Hannah',10, false)
insert into book (title,author,rating,is_lent) values ('Skaza','Hart, Josephine',10, false)
insert into book (title,author,rating,is_lent) values ('Radość dla początkujących','Bauermeister, Erica',10, false)
insert into book (title,author,rating,is_lent) values ('Klub miłośników ginu i zupy z ostryg','Rossiter, Nancy',10, false)
insert into book (title,author,rating,is_lent) values ('Wszystkie smaki namiętności','Feisty, Lilli',10, false)
insert into book (title,author,rating,is_lent) values ('Arsène Lupin, dżentelmen włamywacz','Leblanc, Maurice',10, false)
insert into book (title,author,rating,is_lent) values ('Arsène Lupin kontra Herlock Sholmes','Leblanc, Maurice',10, false)
insert into book (title,author,rating,is_lent) values ('Niezbędnik obserwatorów gwiazd','Quick, Matthew',10, false)
insert into book (title,author,rating,is_lent) values ('Duża ryba','Wallace, Daniel',10, false)
insert into book (title,author,rating,is_lent) values ('Auteczko','Hrabal, Bohumil',10, false)
insert into book (title,author,rating,is_lent) values ('Mistrz i Małgorzata','Bułhakow, Michaił',10, false)
insert into book (title,author,rating,is_lent) values ('Gra w klasy','Cortázar, Julio',10, false)
insert into book (title,author,rating,is_lent) values ('Imię róży','Eco, Umberto',10, false)
insert into book (title,author,rating,is_lent) values ('Ferdydurke','Gombrowicz, Witold',10, false)
insert into book (title,author,rating,is_lent) values ('Blaszany będenek','Grass, Günter',10, false)
insert into book (title,author,rating,is_lent) values ('Przygody dobrego wojaka Szwejka. Tom 1','Hašek, Jaroslav',10, false)
insert into book (title,author,rating,is_lent) values ('Przygody dobrego wojaka Szwejka. Tom 2','Hašek, Jaroslav',10, false)
insert into book (title,author,rating,is_lent) values ('Paragraf 22','Heller, Joseph',10, false)
insert into book (title,author,rating,is_lent) values ('Komu bije dzwon','Hemingway, Ernest',10, false)
insert into book (title,author,rating,is_lent) values ('89 wierszy','Herbert, Zbigniew',10, false)
insert into book (title,author,rating,is_lent) values ('Inny świat','Herling-Grudziński, Gustaw',10, false)
insert into book (title,author,rating,is_lent) values ('Ullisses','Joyce, James',10, false)
insert into book (title,author,rating,is_lent) values ('Proces','Kafka, Franz',10, false)
insert into book (title,author,rating,is_lent) values ('Czarodziejska góra. Tom 1','Mann, Tomasz',10, false)
insert into book (title,author,rating,is_lent) values ('Czarodziejska góra. Tom 2','Mann, Tomasz',10, false)
insert into book (title,author,rating,is_lent) values ('Sto lat samotności','Márquez, Gabriel Gracía',10, false)
insert into book (title,author,rating,is_lent) values ('Kubuś Puchatek. Chatka Puchatka','Milne, Alan Alexander',10, false)
insert into book (title,author,rating,is_lent) values ('Folwark zwierzęcy','Orwell, George',10, false)
insert into book (title,author,rating,is_lent) values ('Rok 1894','Orwell, George',10, false)
insert into book (title,author,rating,is_lent) values ('Doktor Żywago','Pasternak, Boris',10, false)
insert into book (title,author,rating,is_lent) values ('W poszukiwaniu straconego czasu. Tom 1','Proust, Marcel',10, false)
insert into book (title,author,rating,is_lent) values ('W poszukiwaniu straconego czasu. Tom 2','Proust, Marcel',10, false)
insert into book (title,author,rating,is_lent) values ('W poszukiwaniu straconego czasu. Tom 3','Proust, Marcel',10, false)
insert into book (title,author,rating,is_lent) values ('W poszukiwaniu straconego czasu. Tom 4','Proust, Marcel',10, false)
insert into book (title,author,rating,is_lent) values ('W poszukiwaniu straconego czasu. Tom 5','Proust, Marcel',10, false)
insert into book (title,author,rating,is_lent) values ('W poszukiwaniu straconego czasu. Tom 6','Proust, Marcel',10, false)
insert into book (title,author,rating,is_lent) values ('W poszukiwaniu straconego czasu. Tom 7','Proust, Marcel',10, false)
insert into book (title,author,rating,is_lent) values ('Mały Książę','Saint-Exupéry, Antoine de',10, false)
insert into book (title,author,rating,is_lent) values ('Sklepy cynamonowe. Sanatorium pod Klepsydrą','Schulz, Bruno',10, false)
insert into book (title,author,rating,is_lent) values ('Archipelag GUŁag. Tom 1','Sołżenicyn, Aleksander',10, false)
insert into book (title,author,rating,is_lent) values ('Archipelag GUŁag. Tom 2','Sołżenicyn, Aleksander',10, false)
insert into book (title,author,rating,is_lent) values ('Archipelag GUŁag. Tom 3','Sołżenicyn, Aleksander',10, false)
insert into book (title,author,rating,is_lent) values ('Cichy Don. Tom 1','Szołochow, Michaił',10, false)
insert into book (title,author,rating,is_lent) values ('Cichy Don. Tom 2','Szołochow, Michaił',10, false)
insert into book (title,author,rating,is_lent) values ('Cichy Don. Tom 3','Szołochow, Michaił',10, false)
insert into book (title,author,rating,is_lent) values ('Cichy Don. Tom 4','Szołochow, Michaił',10, false)
insert into book (title,author,rating,is_lent) values ('Władca Pierścieni. Drużyna Pierścienia','Tolkien, John Ronald Reuel',10, false)
insert into book (title,author,rating,is_lent) values ('Władca Pierścieni. Dwie wieże','Tolkien, John Ronald Reuel',10, false)
insert into book (title,author,rating,is_lent) values ('Władca Pierścieni. Powrót króla','Tolkien, John Ronald Reuel',10, false)
insert into book (title,author,rating,is_lent) values ('Moje francuskie życie','Archer, Vicki',10, false)
insert into book (title,author,rating,is_lent) values ('Paryż','Sempé, Jean-Jacques',10, false)
insert into book (title,author,rating,is_lent) values ('Poradnik perfekcyjnej pani domu','Rozenek, Małgorzata',10, false)
insert into book (title,author,rating,is_lent) values ('Mieć piękny umysł','Bono, Edward de',10, false)
insert into book (title,author,rating,is_lent) values ('Perfekcyjny makijaż','Brown, Bobbi',10, false)
insert into book (title,author,rating,is_lent) values ('Taft','Patchett, Ann',10, false)
insert into book (title,author,rating,is_lent) values ('House of Cards','Dobbs, Michael',10, false)
insert into book (title,author,rating,is_lent) values ('House of Cards. Ograć króla','Dobbs, Michael',10, false)
insert into book (title,author,rating,is_lent) values ('Losing Hope','Hoover, Colleen',10, false)
insert into book (title,author,rating,is_lent) values ('Wybacz mi, Leonardzie','Quick, Matthew',10, false)
insert into book (title,author,rating,is_lent) values ('Papierowe miasta','Green, John',10, false)
insert into book (title,author,rating,is_lent) values ('Igrzyska Śmierce','Collins, Suzanne',10, false)
insert into book (title,author,rating,is_lent) values ('W pierścieniu ognia','Collins, Suzanne',10, false)
insert into book (title,author,rating,is_lent) values ('Kosogłos','Collins, Suzanne',10, false)
insert into book (title,author,rating,is_lent) values ('Kwiaty na poddaszu','Andrews, Virginia C.',10, false)
insert into book (title,author,rating,is_lent) values ('Ostre przedmioty','Flynn, Gillian',10, false)
insert into book (title,author,rating,is_lent) values ('Mroczny zakątek','Flynn, Gillian',10, false)
insert into book (title,author,rating,is_lent) values ('Zaginiona dziewczyna','Flynn, Gillian',10, false)
insert into book (title,author,rating,is_lent) values ('Wędrówka przez słońce','Addison, Corban',10, false)
insert into book (title,author,rating,is_lent) values ('Dziewczęta z Szanghaju','See, Lisa',10, false)
insert into book (title,author,rating,is_lent) values ('Wyspa skazańców','Lehane, Dennis',10, false)
insert into book (title,author,rating,is_lent) values ('Rzeka tajemnic','Lehane, Dennis',10, false)
insert into book (title,author,rating,is_lent) values ('Wielki Gatsby','Fitzgerald, Francis Scott',10, false)
insert into book (title,author,rating,is_lent) values ('Pięćdziesiąt twarzy Greya','James, E L',10, false)
insert into book (title,author,rating,is_lent) values ('Pięść Dawida. Tajne służby Izraela','Górski, Artur',10, false)
insert into book (title,author,rating,is_lent) values ('Wampir Lestat','Rice, Anne',10, false)
insert into book (title,author,rating,is_lent) values ('Cmętarz Zwieżąt','King, Stephen',10, false)
insert into book (title,author,rating,is_lent) values ('Potem…','Musso, Guillaume',10, false)
insert into book (title,author,rating,is_lent) values ('Jeden dzień','Nicholls, David',10, false)
insert into book (title,author,rating,is_lent) values ('Kwiat pustyni','Dirie, Waris',10, false)
insert into book (title,author,rating,is_lent) values ('Zoo City','Beukes, Lauren',10, false)
insert into book (title,author,rating,is_lent) values ('Obietnica Łucji','Gąsiorowska, Dorota',10, false)
insert into book (title,author,rating,is_lent) values ('Snajper','Kyle, Chris',10, false)
insert into book (title,author,rating,is_lent) values ('100 czystych stron','Massarotto, Cyril',10, false)
insert into book (title,author,rating,is_lent) values ('Co widział pies i inne przygody','Gladwell, Malcolm',10, false)
insert into book (title,author,rating,is_lent) values ('Wyspa łza','Bator, Joanna',10, false)